name = "benward-contact"
type = "javascript"

account_id = "e5b027fcf398b4a8067e8c415dc299d4"
workers_dev = true
compatibility_date = "2024-07-23"
node_compat = true

main = "./dist/index.js"  # Path to your main script

kv_namespaces = [
  { binding = "BENWARD_CONTACT_KV", id = "f44fada6ae034e4ea5dea4efe64a43cd" }
]

send_email = [
  {type = "send_email", name = "emailSender", destination_address = "ben@benward.io"}
]

[env.production]
route = "benward.io/*"
zone_id = "02faaa083fe91320956b6c3021ecbd38"
